FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Fn API

FnProject Automation and Orchestration API.

# Group Set the Environment

## Setup [/setup]

### Configure [POST]

Initial setup required to connect to the Oracle Cloud Infrastructure. API keys are c/p. Keep newline (\n) formatting.

+ Request (application/json)

        {
            "user_id": 1,
            "env_name": "des",
            "fingerprint": "fb:93:b0:6c:ac:f2:42:c7:97:00:xxx",
            "private_key": "-----BEGIN RSA PRIVATE KEY-----\n-----END RSA PRIVATE KEY-----",
            "user_ocid": "ocid1.user.oc1..xxxx",
            "tenancy_ocid": "ocid1.tenancy.oc1.xxxxx",
            "region": "us-ashburn-1"
        }

+ Response 200 (application/json)

        {
            "environment": "des",
            "success": true
        }
        
## Group Network

## VCN [/vcn]

### Create VCN [POST]

Create a Virtual Cloud Network.

+ Request (application/json)

        {
            "user_id": 1,
            "env_name": "des",
            "compartment_id": "ocid1.compartment.oc1.xxx",
            "cidr_block": "10.0.0.0/16",
            "name": "VCNFaaS"
        }

+ Response 200 (application/json)

        {
            "cidr_block": "10.0.0.0/16",
            "compartment_id": "ocid1.compartment.oc1.xxx",
            "default_dhcp_options_id": "ocid1.dhcpoptions.oc1.iad.xxx",
            "default_route_table_id": "ocid1.routetable.oc1.iad.xxx",
            "default_security_list_id": "ocid1.securitylist.oc1.iad.xx",
            "display_name": "VCNFaaS",
            "dns_label": null,
            "id": "ocid1.vcn.oc1.iad.xxx",
            "lifecycle_state": "AVAILABLE",
            "time_created": 1523918858,
            "vcn_domain_name": null
        }

## Subnet [/subnet]

### Create Subnet [POST]

Create a Subnet given the VCN.

+ Request (application/json)

        {
            "user_id": 1,
            "env_name": "des",
            "compartment_id": "ocid1.compartment.oc1.xxx",
            "cidr_block": "10.0.2.0/24",
            "name": "SubnetFaaS",
            "ad":"yKpP:US-ASHBURN-AD-1",
            "vcn_id": "ocid1.vcn.oc1.xxx"
        }

+ Response 200 (application/json)

        {
            "availability_domain": "yKpP:US-ASHBURN-AD-1",
            "cidr_block": "10.0.2.0/24",
            "compartment_id": "ocid1.compartment.oc1..aaaaaaaazx6rv4c3fw4xp27o35e237g5jwi5bdullgryj35qzhxcugypi6da",
            "display_name": "SubnetFaaS",
            "dns_label": null,
            "id": "ocid1.subnet.oc1.iad.aaaaaaaazav37jc42glcheocencycxv24vel6ybv2ch2dgglcemlbf6wtyla",
            "lifecycle_state": "PROVISIONING",
            "prohibit_public_ip_on_vnic": false,
            "route_table_id": "ocid1.routetable.oc1.iad.aaaaaaaa5bseuqlg2lsknukc32zcbzbvnh574prh7bobpyuyswjgernxcvra",
            "security_list_ids": "['ocid1.securitylist.oc1.iad.aaaaaaaavq67huovzipzhkslc54u7pis54av3zcf3da2uy5gewxvfn3upbna']",
            "subnet_domain_name": null,
            "time_created": 1523919820,
            "vcn_id": "ocid1.vcn.oc1.iad.aaaaaaaaiewj62zsi4bszfp623ktn7rswarojrictzo2sdk57rjwoxbd6lyq",
            "virtual_router_ip": "10.0.2.1",
            "virtual_router_mac": "00:00:17:87:A7:C4"
        }

## Gateway [/gateway]

### Create Gateway [POST]

Create a Gateway given the VCN.

+ Request (application/json)

        {
            "user_id": 1,
            "env_name": "des",
            "compartment_id": "ocid1.compartment.oc1..aaaaaaaazx6rv4c3fw4xp27o35e237g5jwi5bdullgryj35qzhxcugypi6da",
            "cidr_block": "10.0.2.0/24",
            "name": "GatewayFaaS",
            "vcn_id": "ocid1.vcn.oc1.iad.aaaaaaaaiewj62zsi4bszfp623ktn7rswarojrictzo2sdk57rjwoxbd6lyq",
            "default_route_table_id": "ocid1.routetable.oc1.iad.aaaaaaaa5bseuqlg2lsknukc32zcbzbvnh574prh7bobpyuyswjgernxcvra"
        }

+ Response 200 (application/json)

        {
            "compartment_id": "ocid1.compartment.oc1..aaaaaaaazx6rv4c3fw4xp27o35e237g5jwi5bdullgryj35qzhxcugypi6da",
            "display_name": "GatewayFaaS",
            "id": "ocid1.internetgateway.oc1.iad.aaaaaaaatspscfcu252fd3miulstnryuvb4gnpm6lnjkdmw65hklpxbkkyoa",
            "is_enabled": "True",
            "lifecycle_state": "AVAILABLE",
            "time_created": "1523920797",
            "vcn_id": "ocid1.vcn.oc1.iad.aaaaaaaaiewj62zsi4bszfp623ktn7rswarojrictzo2sdk57rjwoxbd6lyq"
        }
        
## Group Compute 

## Image [/images]

### Get all Images [POST]

Gets all images available in a compartment.

+ Request (application/json)

        {
            "user_id": 1,
            "env_name": "des",
            "compartment_id": "ocid1.compartment.oc1.xxxx"
        }
        
+ Response 200 (application/json)

        {
            "Canonical Ubuntu 14.04": "ocid1.image.oc1.iad.aaaaaaaazphfcdl2cls3jp2n3tu6ifxzwgwcufb3fh24komedjvtyq74sckq",
            "Canonical Ubuntu 16.04": "ocid1.image.oc1.iad.aaaaaaaa4mgxc6fgpor35gmf57liqriu7kekhcif52h4esgmwrnuk6vyucsq",
            "CentOS 6.9": "ocid1.image.oc1.iad.aaaaaaaatg3iqwyr5jusvsa7u5zjkjydqzjfgbx4mgx5blxaarmv2rikwn2a",
            "CentOS 7": "ocid1.image.oc1.iad.aaaaaaaau2yljlt33cvkweyknohgj6l5abm2thznvcqdvr5epgnce3jlrcsq",
            "Oracle Linux 6.9": "ocid1.image.oc1.iad.aaaaaaaasjserhtqohvkr7dmrqtxwrudq72wp72vowna65cbfqvdjeterq6a",
            "Oracle Linux 7.4": "ocid1.image.oc1.iad.aaaaaaaaiuk7jmajtgnvnv7ihprkymreom2lqyoppzr6h2w3h56cwos5cnvq",
            "Windows Server 2008 R2": "ocid1.image.oc1.iad.aaaaaaaawticvxqe6icrynkhw2wsmjm2naxwxdp3oykyqmlplxfb4cjx6jyq",
            "Windows Server 2012 R2 Standard": "ocid1.image.oc1.iad.aaaaaaaagjdk5pphn2hlgt5vlzww35mhpsfsf6cjdwql2xu5kgohajtbhlga",
            "Windows Server 2016 Datacenter": "ocid1.image.oc1.iad.aaaaaaaatlfpzhsy6vqcpt7c2sm3yn25tpfklcljtypvszzw4qwoptjypa7q",
            "Windows Server 2016 Standard": "ocid1.image.oc1.iad.aaaaaaaaet2lacxv5s7pjar4j2v2j5sg2bjbndvh45vufckpkeyc3ew2ggvq"
        }
        
## Compute [/compute]

### Create a Compute Instance [POST]

Creates a compute instance in a compartment.

+ Request (application/json)

        {
            "ad": "yKpP:US-ASHBURN-AD-1",
            "compartment_id": "ocid1.compartment.oc1.xxx",
            "name": "FaaSCompute",
            "image_id": "ocid1.image.oc1.iad.xxx",
            "shape": "VM.Standard2.1",
            "subnet_id": "ocid1.subnet.oc1.iad.xxx",
            "user_id": 1,
            "env_name": "des"
        }
        
+ Response 200 (application/json)

        {}